import { UTApi } from 'uploadthing/server'
import { readFile, writeFile, mkdir } from 'fs/promises'
import { existsSync } from 'fs'
import { resolve, basename, extname } from 'path'
import { createHash } from 'crypto'

interface SeedField {
  pdfFieldName: string
  sourceType: 'database' | 'custom' | 'qr_code'
  sourceKey?: string
  displayLabel: string
  fontFamily?: string
  fontSize?: number
  fontSource?: 'google' | 'uploaded'
  uploadedFontRef?: string
  isEnabled?: boolean
  sortOrder?: number
  customDefaultValue?: string
  customOverridable?: boolean
}

interface SeedPdfTemplate {
  name: string
  description?: string
  fileName: string
  fields: SeedField[]
}

interface SeedFont {
  ref: string
  fileName: string
}

interface Manifest {
  pdfTemplates: SeedPdfTemplate[]
  fonts: SeedFont[]
}

interface UploadResult {
  name: string
  key: string
  ufsUrl: string
}

const ROOT = process.cwd()
const SEED_FILES_DIR = resolve(ROOT, 'supabase', 'seed-files')
const MANIFEST_PATH = resolve(SEED_FILES_DIR, 'manifest.json')
const OUTPUT_PATH = resolve(SEED_FILES_DIR, 'seed-files.sql')
const ENV_PATH = resolve(ROOT, '.env.local')

function deterministicUUID(input: string): string {
  const hash = createHash('sha256').update(input).digest('hex')
  return [
    hash.slice(0, 8),
    hash.slice(8, 12),
    '4' + hash.slice(13, 16),
    '8' + hash.slice(17, 20),
    hash.slice(20, 32),
  ].join('-')
}

function getMimeType(fileName: string): string {
  const ext = extname(fileName).toLowerCase()
  const map: Record<string, string> = {
    '.pdf': 'application/pdf',
    '.ttf': 'font/ttf',
    '.otf': 'font/otf',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
  }
  return map[ext] || 'application/octet-stream'
}

function pgLiteral(val: string | null | undefined): string {
  if (val == null) return 'NULL'
  return "'" + val.replace(/'/g, "''") + "'"
}

async function loadEnv(): Promise<void> {
  if (process.env.UPLOADTHING_TOKEN) return
  try {
    const content = await readFile(ENV_PATH, 'utf-8')
    for (const line of content.split('\n')) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith('#')) continue
      const eqIdx = trimmed.indexOf('=')
      if (eqIdx === -1) continue
      const key = trimmed.slice(0, eqIdx).trim()
      let val = trimmed.slice(eqIdx + 1).trim()
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1)
      }
      process.env[key] = val
    }
  } catch {
    // .env.local not found, continue
  }
}

async function uploadFile(
  utapi: UTApi,
  filePath: string,
  fileName: string,
): Promise<UploadResult> {
  const buffer = await readFile(filePath)
  const blob = new Blob([buffer], { type: getMimeType(fileName) })
  const file = Object.assign(blob, { name: fileName })
  const result = await utapi.uploadFiles(file)

  if (result.error) {
    throw new Error(`Upload failed for ${fileName}: ${result.error.message}`)
  }

  return { name: fileName, key: result.data.key, ufsUrl: result.data.ufsUrl }
}

function generateSql(
  templates: SeedPdfTemplate[],
  fontResults: Map<string, UploadResult>,
  pdfResults: UploadResult[],
): string {
  const lines: string[] = [
    '-- =================================================================',
    '-- Generated by scripts/seed-upload-files.ts',
    '-- Do not edit manually.',
    '-- Re-run the script to regenerate.',
    '-- =================================================================',
    '',
    '-- ── PDF Templates ────────────────────────────────────────────────',
    '',
  ]

  const templateResults = new Map<string, UploadResult>()
  for (const r of pdfResults) {
    templateResults.set(basename(r.name), r)
  }

  for (const t of templates) {
    const r = templateResults.get(basename(t.fileName))
    if (!r) {
      console.warn(`  ⚠ No upload result for ${t.fileName}, skipping SQL`)
      continue
    }

    const uuid = deterministicUUID('pdf-template:' + t.name)
    const fileKey = r.key

    lines.push(`-- Template: ${t.name}`)
    lines.push(`INSERT INTO pdf_templates (id, name, description, file_url, file_key)`)
    lines.push(
      `VALUES (${pgLiteral(uuid)}, ${pgLiteral(t.name)}, ${pgLiteral(t.description ?? null)}, ${pgLiteral(r.ufsUrl)}, ${pgLiteral(fileKey)});`,
    )
    lines.push('')

    if (t.fields.length > 0) {
      lines.push(`-- Fields for: ${t.name}`)
      lines.push(
        `INSERT INTO pdf_template_fields (template_id, pdf_field_name, source_type, source_key, display_label, font_family, font_size, font_source, uploaded_font_key, is_enabled, custom_default_value, custom_overridable, sort_order)`,
      )

      const values: string[] = []
      for (const f of t.fields) {
        let uploadedFontKey: string | null = null
        if (f.fontSource === 'uploaded' && f.uploadedFontRef) {
          const fontResult = fontResults.get(f.uploadedFontRef)
          uploadedFontKey = fontResult?.key ?? null
          if (!fontResult) {
            console.warn(
              `  ⚠ Font ref "${f.uploadedFontRef}" not found for field "${f.pdfFieldName}"`,
            )
          }
        }

        values.push(
          `  (${pgLiteral(uuid)}, ${pgLiteral(f.pdfFieldName)}, ${pgLiteral(f.sourceType)}, ${pgLiteral(f.sourceKey ?? null)}, ${pgLiteral(f.displayLabel)}, ${pgLiteral(f.fontFamily ?? 'Inter')}, ${f.fontSize ?? 12}, ${pgLiteral(f.fontSource ?? 'google')}, ${pgLiteral(uploadedFontKey)}, ${f.isEnabled ?? true}, ${pgLiteral(f.customDefaultValue ?? null)}, ${f.customOverridable ?? false}, ${f.sortOrder ?? 0})`,
        )
      }

      lines.push('VALUES')
      lines.push(values.join(',\n') + ';')
      lines.push('')
    }
  }

  if (fontResults.size > 0) {
    lines.push('-- ── Font References ────────────────────────────────────────────')
    lines.push(
      '-- These fonts were uploaded to Uploadthing. Use the keys below',
    )
    lines.push(
      '-- in pdf_template_fields.uploaded_font_key when configuring fields.',
    )
    lines.push('')
    for (const [ref, result] of fontResults) {
      lines.push(`-- Font: ${ref}`)
      lines.push(`-- File: ${result.name}`)
      lines.push(`-- Key: ${result.key}`)
      lines.push(`-- URL: ${result.ufsUrl}`)
      lines.push('')
    }
  }

  return lines.join('\n')
}

async function main() {
  console.log('Seed File Upload Script')
  console.log('')

  await loadEnv()
  if (!process.env.UPLOADTHING_TOKEN) {
    console.error('UPLOADTHING_TOKEN not found in environment or .env.local')
    console.error(
      '  Run with: dotenv -e .env.local -- npx tsx scripts/seed-upload-files.ts',
    )
    process.exit(1)
  }

  if (!existsSync(MANIFEST_PATH)) {
    console.error(`Manifest not found: ${MANIFEST_PATH}`)
    console.error('  Create supabase/seed-files/manifest.json')
    process.exit(1)
  }

  const manifestRaw = await readFile(MANIFEST_PATH, 'utf-8')
  const manifest: Manifest = JSON.parse(manifestRaw)

  console.log(
    `Manifest: ${manifest.pdfTemplates.length} template(s), ${manifest.fonts.length} font(s)`,
  )

  const utapi = new UTApi()

  const pdfResults: UploadResult[] = []
  for (const t of manifest.pdfTemplates) {
    const filePath = resolve(SEED_FILES_DIR, t.fileName)
    if (!existsSync(filePath)) {
      console.error(`  File not found: ${filePath}`)
      process.exit(1)
    }
    process.stdout.write(`  Uploading PDF: ${t.fileName}... `)
    const result = await uploadFile(utapi, filePath, basename(t.fileName))
    pdfResults.push(result)
    console.log(`key: ${result.key}`)
  }

  const fontResults = new Map<string, UploadResult>()
  for (const f of manifest.fonts) {
    const filePath = resolve(SEED_FILES_DIR, f.fileName)
    if (!existsSync(filePath)) {
      console.error(`  File not found: ${filePath}`)
      process.exit(1)
    }
    process.stdout.write(`  Uploading font: ${f.fileName}... `)
    const result = await uploadFile(utapi, filePath, basename(f.fileName))
    fontResults.set(f.ref, result)
    console.log(`key: ${result.key}`)
  }

  console.log('')
  console.log('Generating SQL...')
  const sql = generateSql(manifest.pdfTemplates, fontResults, pdfResults)
  await mkdir(SEED_FILES_DIR, { recursive: true })
  await writeFile(OUTPUT_PATH, sql, 'utf-8')
  console.log(`  SQL written to: ${OUTPUT_PATH}`)

  console.log('')
  console.log('━'.repeat(40))
  console.log('Done!')
  console.log(`  ${pdfResults.length} PDF(s) uploaded`)
  console.log(`  ${fontResults.size} font(s) uploaded`)
  console.log('')
  console.log('Next steps:')
  console.log(`  1. Review the SQL in supabase/seed-files/seed-files.sql`)
  console.log('  2. Run `supabase db reset` to apply seeds')
  console.log('  3. Commit the changes to git')
}

main().catch((err) => {
  console.error('Fatal error:', err)
  process.exit(1)
})
