import { UTApi } from 'uploadthing/server'
import { readFile, writeFile, mkdir } from 'fs/promises'
import { existsSync } from 'fs'
import { resolve, basename, extname } from 'path'
import { createHash } from 'crypto'

interface SeedField {
  pdfFieldName: string
  sourceType: 'database' | 'custom' | 'qr_code'
  sourceKey?: string
  displayLabel: string
  fontFamily?: string
  fontSize?: number
  fontSource?: 'google' | 'uploaded'
  uploadedFontRef?: string
  isEnabled?: boolean
  sortOrder?: number
  customDefaultValue?: string
  customOverridable?: boolean
  dateFormat?: 'usa' | 'gb' | 'locale'
  levelFormat?: 'short' | 'text' | 'long'
  textColor?: string
  qrDotsColor?: string
  qrBgColor?: string
  qrDotsType?: string
  qrCornersType?: string
  qrCornersColor?: string
  fontVariant?: string
  multiline?: boolean
}

interface SeedVariantFieldOverrides {
  [fieldPdfName: string]: Record<string, unknown>
}

interface SeedVariant {
  name: string
  fileName: string
  fieldOverrides?: SeedVariantFieldOverrides
}

interface SeedPdfTemplate {
  name: string
  description?: string
  fields: SeedField[]
  variants: SeedVariant[]
}

interface SeedFont {
  ref: string
  name: string
  family?: string
  variant?: string
  fileName: string
}

interface Manifest {
  pdfTemplates: SeedPdfTemplate[]
  fonts: SeedFont[]
}

interface UploadResult {
  name: string
  key: string
  ufsUrl: string
  fileSize: number
}

const ROOT = process.cwd()
const SEED_FILES_DIR = resolve(ROOT, 'supabase', 'seed-files')
const MANIFEST_PATH = resolve(SEED_FILES_DIR, 'manifest.json')
const OUTPUT_PATH = resolve(SEED_FILES_DIR, 'seed-files.sql')
const ENV_PATH = resolve(ROOT, '.env.local')

function parseFontFamilyVariant(fileName: string): { family: string; variant: string } {
  const name = basename(fileName).replace(/\.ttf$/i, '')
  const variantMatch = name.match(/^(.+)-(\d{3}(?:italic)?)$/)
  if (variantMatch) return { family: variantMatch[1], variant: variantMatch[2] }
  const italicMatch = name.match(/^(.+)-italic$/)
  if (italicMatch) return { family: italicMatch[1], variant: 'italic' }
  return { family: name, variant: 'regular' }
}

function deterministicUUID(input: string): string {
  const hash = createHash('sha256').update(input).digest('hex')
  return [
    hash.slice(0, 8),
    hash.slice(8, 12),
    '4' + hash.slice(13, 16),
    '8' + hash.slice(17, 20),
    hash.slice(20, 32),
  ].join('-')
}

function getMimeType(fileName: string): string {
  const ext = extname(fileName).toLowerCase()
  const map: Record<string, string> = {
    '.pdf': 'application/pdf',
    '.ttf': 'font/ttf',
    '.otf': 'font/otf',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
  }
  return map[ext] || 'application/octet-stream'
}

function pgLiteral(val: string | null | undefined): string {
  if (val == null) return 'NULL'
  return "'" + val.replace(/'/g, "''") + "'"
}

async function loadEnv(): Promise<void> {
  if (process.env.UPLOADTHING_TOKEN) return
  try {
    const content = await readFile(ENV_PATH, 'utf-8')
    for (const line of content.split('\n')) {
      const trimmed = line.trim()
      if (!trimmed || trimmed.startsWith('#')) continue
      const eqIdx = trimmed.indexOf('=')
      if (eqIdx === -1) continue
      const key = trimmed.slice(0, eqIdx).trim()
      let val = trimmed.slice(eqIdx + 1).trim()
      if ((val.startsWith('"') && val.endsWith('"')) || (val.startsWith("'") && val.endsWith("'"))) {
        val = val.slice(1, -1)
      }
      process.env[key] = val
    }
  } catch {
    // .env.local not found, continue
  }
}

async function uploadFile(
  utapi: UTApi,
  filePath: string,
  fileName: string,
): Promise<UploadResult> {
  const buffer = await readFile(filePath)
  const blob = new Blob([buffer], { type: getMimeType(fileName) })
  const file = Object.assign(blob, { name: fileName })
  const result = await utapi.uploadFiles(file)

  if (result.error) {
    throw new Error(`Upload failed for ${fileName}: ${result.error.message}`)
  }

  const fileSize = buffer.length
  return { name: fileName, key: result.data.key, ufsUrl: result.data.ufsUrl, fileSize }
}

function generateSql(
  templates: SeedPdfTemplate[],
  manifestFonts: SeedFont[],
  fontResults: Map<string, UploadResult>,
  pdfResults: UploadResult[],
): string {
  const lines: string[] = [
    '-- =================================================================',
    '-- Generated by scripts/seed-upload-files.ts',
    '-- Do not edit manually.',
    '-- Re-run the script to regenerate.',
    '-- =================================================================',
    '',
  ]

  const templateResults = new Map<string, UploadResult>()
  for (const r of pdfResults) {
    templateResults.set(basename(r.name), r)
  }

  // ── Fonts ──────────────────────────────────────────────────────
  if (manifestFonts.length > 0) {
    lines.push('-- ── Fonts ──────────────────────────────────────────────────────')
    lines.push('')
    const fontValues: string[] = []
    for (const mf of manifestFonts) {
      const result = fontResults.get(mf.ref)
      if (!result) {
        console.warn(`  ⚠ No upload result for font "${mf.ref}", skipping`)
        continue
      }
      const fontId = deterministicUUID('pdf-font:' + mf.ref)
      const { family, variant } = mf.family ? { family: mf.family, variant: mf.variant || 'regular' } : parseFontFamilyVariant(mf.fileName)
      fontValues.push(
        `  (${pgLiteral(fontId)}, ${pgLiteral(mf.name)}, ${pgLiteral(family)}, ${pgLiteral(variant)}, ${pgLiteral(result.ufsUrl)}, ${pgLiteral(result.key)}, ${result.fileSize})`,
      )
    }
    if (fontValues.length > 0) {
      lines.push('INSERT INTO pdf_fonts (id, name, family, variant, file_url, file_key, file_size)')
      lines.push('VALUES')
      lines.push(fontValues.join(',\n') + ';')
      lines.push('')
    }
  }

  // ── PDF Templates, Variants & Fields ───────────────────────────
  for (const t of templates) {
    const firstVariant = t.variants[0]
    const firstResult = firstVariant ? templateResults.get(basename(firstVariant.fileName)) : null
    if (!firstResult) {
      console.warn(`  ⚠ No upload result for first variant of "${t.name}", skipping SQL`)
      continue
    }

    const templateId = deterministicUUID('pdf-template:' + t.name)
    lines.push(`-- Template: ${t.name}`)
    lines.push(`INSERT INTO pdf_templates (id, name, description, file_url, file_key)`)
    lines.push(
      `VALUES (${pgLiteral(templateId)}, ${pgLiteral(t.name)}, ${pgLiteral(t.description ?? null)}, ${pgLiteral(firstResult.ufsUrl)}, ${pgLiteral(firstResult.key)});`,
    )
    lines.push('')

    // ── Fields ────────────────────────────────────────────────
    if (t.fields.length > 0) {
      lines.push(`-- Fields for: ${t.name}`)
      lines.push(
        `INSERT INTO pdf_template_fields (id, template_id, pdf_field_name, source_type, source_key, display_label, font_family, font_size, font_source, uploaded_font_key, font_id, is_enabled, custom_default_value, custom_overridable, sort_order, date_format, level_format, text_color, qr_dots_color, qr_bg_color, qr_dots_type, qr_corners_type, qr_corners_color, font_variant, multiline)`,
      )

      const values: string[] = []
      for (const f of t.fields) {
        const fieldId = deterministicUUID('pdf-field:' + t.name + ':' + f.pdfFieldName)

        let uploadedFontKey: string | null = null
        let fontId: string | null = null
        if (f.fontSource === 'uploaded' && f.uploadedFontRef) {
          const fontResult = fontResults.get(f.uploadedFontRef)
          if (fontResult) {
            uploadedFontKey = fontResult.key
            fontId = deterministicUUID('pdf-font:' + f.uploadedFontRef)
          } else {
            console.warn(
              `  ⚠ Font ref "${f.uploadedFontRef}" not found for field "${f.pdfFieldName}"`,
            )
          }
        }

        values.push(
          `  (${pgLiteral(fieldId)}, ${pgLiteral(templateId)}, ${pgLiteral(f.pdfFieldName)}, ${pgLiteral(f.sourceType)}, ${pgLiteral(f.sourceKey ?? null)}, ${pgLiteral(f.displayLabel)}, ${pgLiteral(f.fontFamily ?? 'Inter')}, ${f.fontSize ?? 12}, ${pgLiteral(f.fontSource ?? 'google')}, ${pgLiteral(uploadedFontKey)}, ${fontId ? pgLiteral(fontId) + '::uuid' : 'NULL'}, ${f.isEnabled ?? true}, ${pgLiteral(f.customDefaultValue ?? null)}, ${f.customOverridable ?? false}, ${f.sortOrder ?? 0}, ${pgLiteral(f.dateFormat ?? null)}, ${pgLiteral(f.levelFormat ?? null)}, ${pgLiteral(f.textColor ?? null)}, ${pgLiteral(f.qrDotsColor ?? '#1a1a2e')}, ${pgLiteral(f.qrBgColor ?? '#FFFFFF')}, ${pgLiteral(f.qrDotsType ?? 'rounded')}, ${pgLiteral(f.qrCornersType ?? 'square')}, ${pgLiteral(f.qrCornersColor ?? '#1a1a2e')}, ${pgLiteral(f.fontVariant ?? 'regular')}, ${f.multiline ?? false})`,
        )
      }

      lines.push('VALUES')
      lines.push(values.join(',\n') + ';')
      lines.push('')
    }

    // ── Variants ─────────────────────────────────────────────
    for (let i = 0; i < t.variants.length; i++) {
      const v = t.variants[i]
      const vr = templateResults.get(basename(v.fileName))
      if (!vr) {
        console.warn(`  ⚠ No upload result for variant "${v.name}" of "${t.name}", skipping`)
        continue
      }

      const variantId = deterministicUUID('pdf-variant:' + t.name + ':' + v.name)
      lines.push(`-- Variant: ${v.name} (${t.name})`)
      lines.push(
        `INSERT INTO pdf_template_variants (id, template_id, name, file_url, file_key, sort_order)`,
      )
      lines.push(
        `VALUES (${pgLiteral(variantId)}, ${pgLiteral(templateId)}, ${pgLiteral(v.name)}, ${pgLiteral(vr.ufsUrl)}, ${pgLiteral(vr.key)}, ${i});`,
      )
      lines.push('')

      // ── Field overrides ──────────────────────────────────────
      if (v.fieldOverrides) {
        for (const [fieldPdfName, overrides] of Object.entries(v.fieldOverrides)) {
          const fieldId = deterministicUUID('pdf-field:' + t.name + ':' + fieldPdfName)

          const overrideCols: string[] = ['variant_id', 'field_id']
          const overrideVals: string[] = [pgLiteral(variantId), pgLiteral(fieldId)]

          for (const [key, value] of Object.entries(overrides)) {
            overrideCols.push(key)
            if (typeof value === 'boolean') {
              overrideVals.push(value ? 'TRUE' : 'FALSE')
            } else if (value === null || value === undefined) {
              overrideVals.push('NULL')
            } else if (typeof value === 'number') {
              overrideVals.push(String(value))
            } else {
              overrideVals.push(pgLiteral(String(value)))
            }
          }

          lines.push(`INSERT INTO pdf_template_field_overrides (${overrideCols.join(', ')})`)
          lines.push(`VALUES (${overrideVals.join(', ')});`)
          lines.push('')
        }
      }
    }
  }

  return lines.join('\n')
}

async function main() {
  console.log('Seed File Upload Script')
  console.log('')

  await loadEnv()
  if (!process.env.UPLOADTHING_TOKEN) {
    console.error('UPLOADTHING_TOKEN not found in environment or .env.local')
    console.error(
      '  Run with: dotenv -e .env.local -- npx tsx scripts/seed-upload-files.ts',
    )
    process.exit(1)
  }

  if (!existsSync(MANIFEST_PATH)) {
    console.error(`Manifest not found: ${MANIFEST_PATH}`)
    console.error('  Create supabase/seed-files/manifest.json')
    process.exit(1)
  }

  const manifestRaw = await readFile(MANIFEST_PATH, 'utf-8')
  const manifest: Manifest = JSON.parse(manifestRaw)

  console.log(
    `Manifest: ${manifest.pdfTemplates.length} template(s), ${manifest.fonts.length} font(s)`,
  )

  const utapi = new UTApi()

  const pdfResults: UploadResult[] = []
  const uniquePdfFiles = new Set<string>()
  for (const t of manifest.pdfTemplates) {
    for (const v of t.variants) {
      if (uniquePdfFiles.has(v.fileName)) continue
      uniquePdfFiles.add(v.fileName)

      const filePath = resolve(SEED_FILES_DIR, v.fileName)
      if (!existsSync(filePath)) {
        console.error(`  File not found: ${filePath}`)
        process.exit(1)
      }
      process.stdout.write(`  Uploading PDF: ${v.fileName}... `)
      const result = await uploadFile(utapi, filePath, basename(v.fileName))
      pdfResults.push(result)
      console.log(`key: ${result.key}`)
    }
  }

  const fontResults = new Map<string, UploadResult>()
  for (const f of manifest.fonts) {
    const filePath = resolve(SEED_FILES_DIR, f.fileName)
    if (!existsSync(filePath)) {
      console.error(`  File not found: ${filePath}`)
      process.exit(1)
    }
    process.stdout.write(`  Uploading font: ${f.fileName}... `)
    const result = await uploadFile(utapi, filePath, basename(f.fileName))
    fontResults.set(f.ref, result)
    console.log(`key: ${result.key}`)
  }

  console.log('')
  console.log('Generating SQL...')
  const sql = generateSql(manifest.pdfTemplates, manifest.fonts, fontResults, pdfResults)
  await mkdir(SEED_FILES_DIR, { recursive: true })
  await writeFile(OUTPUT_PATH, sql, 'utf-8')
  console.log(`  SQL written to: ${OUTPUT_PATH}`)

  console.log('')
  console.log('━'.repeat(40))
  console.log('Done!')
  console.log(`  ${pdfResults.length} PDF(s) uploaded`)
  console.log(`  ${fontResults.size} font(s) uploaded`)
  console.log('')
  console.log('Next steps:')
  console.log(`  1. Review the SQL in supabase/seed-files/seed-files.sql`)
  console.log('  2. Run `supabase db reset` to apply seeds')
  console.log('  3. Commit the changes to git')
}

main().catch((err) => {
  console.error('Fatal error:', err)
  process.exit(1)
})
